import functools as ft
import logging
import os
from datetime import datetime, timedelta
from typing import Dict, List

from databricks.connect import DatabricksSession  # type: ignore
from prefect import get_run_logger  # type: ignore
from pyspark.sql import DataFrame  # type: ignore
from pyspark.sql import functions as f  # type: ignore

from data_engineering.core.utils import load_yaml_file

spark = DatabricksSession.builder.getOrCreate()
logger = logging.getLogger(__name__)


def get_date_range_check():
    """Generates the start date and end date required for automatic validation.

    Args:
        None.

    Returns:
        start_dt: start date
        end_dt: end date
    """
    if not os.getenv("start_dt") or not os.getenv("end_dt"):
        start_date = (
            datetime.today() + timedelta(days=-datetime.today().day)
        ).strftime("%Y-%m-") + "01"
        end_date = (datetime.today() + timedelta(days=-datetime.today().day)).strftime(
            "%Y-%m-%d"
        )
    else:
        start_date = os.getenv("start_dt")
        end_date = os.getenv("end_dt")

    return start_date, end_date


def dynamic_query(p_list, p_query):
    """Execute a dynamic query with the list of tables provided

    Args:
        p_list (list): Tables.
        p_query (str): Query to execute.

    Returns:
         DataFrame: Df with the data generated by the query
    """
    if not p_list:
        return None

    list_cols = []
    for item in p_list:
        query_execute = p_query + item
        execute = spark.sql(query_execute).withColumn("tabla", f.lit(item))
        list_cols.append(execute)

    result = ft.reduce(DataFrame.unionAll, list_cols)

    return result


def schema_tables():
    """Used to generate a list of tables with their schema

    Args:
        None

    Returns:
         List: Tables with their schema
    """
    root_dir = os.path.dirname(os.path.dirname(__file__))
    company = load_yaml_file(
        os.path.join(root_dir, "env/base/global_settings.yml")
    ).get("company")

    env = os.getenv("env")
    workflow = os.getenv("workflow")

    environment_catalog = "sandbox" if env not in ["prod", "dev"] else env

    schema = f"{env}_{workflow}"

    catalog = f"{company}_{environment_catalog}_de"

    spark.sql(f"use catalog {catalog}")

    list_table = [
        schema + "." + row.tableName
        for row in spark.sql(f"show tables in {schema}").collect()
    ]

    return list_table


def table_columns(p_list_tables, date_column_frequencies):
    """Generates the columns from the list of provided tables

    Args:
        p_list_tables (list): List of table names.
        date_column_frequencies (dict): Dictionary with date column names
        and their frequencies.

    Returns:
         DataFrame: Dataframe with the names of the tables and their columns
    """
    df_table_columns = dynamic_query(p_list_tables, "show columns from ")
    if df_table_columns is None:
        return spark.createDataFrame(
            [], schema="tabla string, columna string, tipo_tabla string"
        )

    # Get column names from the dictionary keys
    column_names = list(date_column_frequencies.keys())

    df_final = df_table_columns.filter(f.col("col_name").isin(column_names)).select(
        f.col("tabla"),
        f.col("col_name").alias("columna"),
        f.when(f.col("col_name") == "fecha_transaccion", f.lit("transaccional"))
        .when(f.col("col_name") == "fecha_informacion", f.lit("snapshot"))
        .when(f.col("col_name") == "fecha_catalogo", f.lit("catalogo"))
        .when(f.col("col_name") == "_observ_end_dt", f.lit("snapshot"))
        .otherwise(f.lit("unknown"))
        .alias("tipo_tabla"),
    )

    return df_final


def date_sequence_task(p_start_dt, p_end_dt, p_filter_date):
    """Sequence dates from the previous month.

    Args:
        p_start_dt: start date
        p_end_dt: end date
        p_filter_date: filter to generate the necessary dates

    Returns:
         DataFrame: Date dataframe
    """

    df_date_sequence = spark.sql(
        f"with date_range as( \
        select to_date('{p_start_dt}') as start_dt, to_date('{p_end_dt}') as end_dt \
        ) select fecha_informacion \
         from(select \
             explode(sequence(start_dt, end_dt, interval 1 day)) as fecha_informacion \
         from date_range) \
         where (case \
                when fecha_informacion = last_day(fecha_informacion) \
                    then 1 else 0 end) in ({p_filter_date})"
    )

    return df_date_sequence


def all_dates_task(p_prev_month_df, p_table_list):
    """Name of the tables with all the days of the previous month.

    Args:
        p_prev_month_df (DataFrame): dates of the previous month.
        p_table_list (List): Table list.

    Returns:
         DataFrame: DataFrame with all tables and dates.
    """
    df_list = []

    if p_table_list:
        for table in p_table_list:
            df_union = p_prev_month_df.select(
                f.col("fecha_informacion"), f.lit(table).alias("tabla")
            )
            df_list.append(df_union)
        return ft.reduce(DataFrame.unionAll, df_list)
    else:
        return None


def count_records(p_df_table, p_start_dt, p_end_dt):
    """Record count per table.

    Args:
        p_df_table (DataFrame): Dates of the previous month and table
        p_start_dt (str): Start date.
        p_end_dt (str): End date.

    Returns:
         DataFrame: DataFrame with Record count per table.
    """
    df_count_records = (
        p_df_table.filter(f.col("fecha_informacion").between(p_start_dt, p_end_dt))
        .groupBy(f.col("fecha_informacion"), f.col("tabla"))
        .agg(f.count("*").alias("cnt"))
    )

    return df_count_records


def evaluate_missing_information(
    df: DataFrame, error_message: str, custom_validations: Dict[str, int] = None
) -> None:
    missing_dates_df = df.filter(f.col("cnt") == 0)
    logger = get_run_logger()
    logger.info("QA: Inspecting missing information across %d tables", df.count())
    if not missing_dates_df.head(1):
        logger.info("✅     QA: No missing information detected")
        return

    group_columns: List[str] = ["tabla", "tipo_tabla"]
    group_columns.append("columna")

    missing_dates2_df = (
        missing_dates_df.withColumn(
            "fecha_informacion_norm",
            f.when(
                (f.col("tipo_tabla") == "catalogo") & (f.col("columna") == "full_load"),
                f.col("fecha_informacion"),
            ).otherwise(f.last_day(f.col("fecha_informacion"))),
        )
        .groupBy(*group_columns, "fecha_informacion_norm")
        .count()
        .withColumnRenamed("fecha_informacion", "date_without_information")
        .withColumnRenamed("fecha_informacion_norm", "fecha_informacion")
    )

    if custom_validations:
        map_entries: List[f.Column] = []
        for key, value in custom_validations.items():
            map_entries.extend([f.lit(key), f.lit(value)])

        missing_dates_custom_df = missing_dates2_df.withColumn(
            "custom_validations", f.create_map(*map_entries)
        )
        custom_domain_prefixes = f.array(
            *[f.lit(key) for key in custom_validations.keys()]
        )

        missing_dates_custom_df = missing_dates_custom_df.withColumn(
            "matched_keys",
            f.filter(custom_domain_prefixes, lambda k: f.col("tabla").contains(k)),
        )
        missing_dates_custom_df = missing_dates_custom_df.filter(
            ~(f.col("tipo_tabla") == "transaccional")
            | (f.size(f.col("matched_keys")) == 0)
            | (
                f.size(
                    f.filter(
                        f.col("matched_keys"),
                        lambda k: f.col("custom_validations")[k] < f.col("count"),
                    )
                )
                > 0
            )
        )
    missing_dates_custom_df = missing_dates_custom_df.select(
        f.col("tabla"),
        f.col("tipo_tabla"),
        f.col("columna"),
        f.date_format(f.col("fecha_informacion"), "yyyy-MM").alias(
            "month_without_data"
        ),
    )

    missing_rows = missing_dates_custom_df.collect()
    if not missing_rows:
        logger.info("QA: No missing information detected")
        return

    if (missing_dates_custom_df.count()) > 0:
        logger.info("QA: Missing information detected Monthly")
        # list_rows = missing_rows
        result = [list(row) for row in missing_rows]
        for item in result:
            print(item)

        if missing_dates_df.filter(f.col("tipo_tabla") == "transaccional").count() > 0:
            logger.info("QA: Missing information detected detailed.")

            missing_rows_detailed = missing_dates_df.select(
                f.col("tabla"),
                f.col("tipo_tabla"),
                f.col("columna"),
                f.date_format(f.col("fecha_informacion"), "yyyy-MM-dd"),
            ).collect()

            ls_missing_dates = [list(row) for row in missing_rows_detailed]
            for item in ls_missing_dates:
                print(item)

        raise TypeError(error_message)

    raise RuntimeError(error_message)


def collect_tables_for_column(df_table_type: DataFrame, column_name: str) -> List[str]:
    return [
        row["tabla"]
        for row in (
            df_table_type.filter(f.col("columna") == column_name)
            .select(f.col("tabla"))
            .distinct()
            .collect()
        )
    ]
